### PR TITLE
Allow to match sockets using ServerSocketPredicate

### LINKED ISSUE #24: Allow to match sockets using ServerSocketPredicate
The basic concept of Cettia is "select some sockets and do something with them". In order for users to do this intuitively, we need to provide a method to match sockets first.

* [x] Implement `Sentence select(ServerSocketPredicate predicate)` method in `Server`

It should create a Sentence that will match the given predicate for sockets. For the definition of `ServerSocketPredicate`, see @ralscha's https://github.com/cettia/cettia-java-server/issues/22#issuecomment-408596569. Here's an example:

```java
server.select(socket -> socket.tags().stream().foo.bar).send("event", data);
```

### PR DESCRIPTION
**Pull request by flowersinthesand**
Fixes #24

### CODE REVIEW

**Comment by flowersinthesand** [comment]
@ralscha I tried to implement your idea https://github.com/cettia/cettia-java-server/issues/22#issuecomment-408596569. Could you review this PR when you get a chance? The following methods are added in Server:

- `Sentence select(ServerSocketPredicate predicate);`
- `Server select(ServerSocketPredicate predicate, SerializableAction<ServerSocket> action);`

For example, it can be used to implement 'send except me' like this.

```java
String exclude = socket.id();
server.select(s -> !s.id().equals(exclude)).send("chat", msg);
```

Here are some points:

- `ServerSocketPredicate` will extend `Function<ServerSocket>` of Java 8 after dropping support for Java 7.
- Javadoc will be replaced and unit tests will be added in 1.1.0.

**Comment by ralscha** [comment]
Hi
Looks very good.
I was thinking about the name `select`. It does not really match with `all`. Maybe `some` would be a better name. I'm not a native english speaker, so I'm not sure if this makes more sense or maybe there is a better word.
```
//send message to some clients
server.some(s -> !s.id().equals(exclude)).send("chat", msg);
//send message to all clients
server.all().send("chat", msg);
```

**Comment by flowersinthesand** [comment]
I'm not a native English speaker too ;) I was thinking a verb is better than a noun since it accepts a predicate and any other selectors can be built on top of that method.

Now I'm thinking that `find` may be better than `select` simply because there are too many variable names starting with `s` e.g. socket, skt, s, server.  🙃

**Comment by ralscha** [comment]
I like `find`. I was just comparing it to `all` which is also not a verb. But you are right a verb makes more sense because it does something with the predicate. 

Other methods in the Java library that accept a Predicate are `filter` and `removeIf`.      
I guess `filter`  does not make sense here. We don't filter the server. 

I would go with `find`. I like it better than `select`.

**Comment by flowersinthesand** [comment]
Great! Thanks for your opinion.

**Pull request merged**
